## Checking the dataset

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
online_retail = fetch_ucirepo(id=352) 
  
# data (as pandas dataframes) 
X_online_retail = online_retail.data.features 
y_online_retail = online_retail.data.targets 
  
# metadata 
print(online_retail.metadata) 
  
# variable information 
print(online_retail.variables)

{'uci_id': 352, 'name': 'Online Retail', 'repository_url': 'https://archive.ics.uci.edu/dataset/352/online+retail', 'data_url': 'https://archive.ics.uci.edu/static/public/352/data.csv', 'abstract': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.', 'area': 'Business', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate', 'Sequential', 'Time-Series'], 'num_instances': 541909, 'num_features': 6, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': None, 'index_col': ['InvoiceNo', 'StockCode'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Oct 21 2024', 'dataset_doi': '10.24432/C5BW33', 'creators': ['Daqing Chen'], 'intro_paper': {'ID': 361, 'type': 'NATIVE', 'title': 'Data mining for the online retail industry: A case study of RFM model-based customer segmentation using data mining', 'authors': 'Daqing Chen, Sai Laing Sain, Kun Guo', 'venue': 'Journal of Database Marketing and Customer Strategy Management, Vol. 19, No. 3', 'year': 2012, 'journal': None, 'DOI': '10.1057/dbm.2012.17', 'URL': 'https://www.semanticscholar.org/paper/e43a5a90fa33d419df42e485099f8f08badf2149', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.The company mainly sells unique all-occasion gifts. Many customers of the company are wholesalers.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation. \nStockCode: Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.\nDescription: Product (item) name. Nominal.\nQuantity: The quantities of each product (item) per transaction. Numeric.\t\nInvoiceDate: Invoice Date and time. Numeric, the day and time when each transaction was generated.\nUnitPrice: Unit price. Numeric, Product price per unit in sterling.\nCustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.\nCountry: Country name. Nominal, the name of the country where each customer resides. ", 'citation': None}}
          name     role         type demographic  \
0    InvoiceNo       ID  Categorical        None
1    StockCode       ID  Categorical        None
2  Description  Feature  Categorical        None
3     Quantity  Feature      Integer        None
4  InvoiceDate  Feature         Date        None
5    UnitPrice  Feature   Continuous        None
6   CustomerID  Feature  Categorical        None
7      Country  Feature  Categorical        None

                                         description     units missing_values
0  a 6-digit integral number uniquely assigned to...      None             no
1  a 5-digit integral number uniquely assigned to...      None             no
2                                       product name      None             no
3  the quantities of each product (item) per tran...      None             no
4  the day and time when each transaction was gen...      None             no
5                             product price per unit  sterling             no
6  a 5-digit integral number uniquely assigned to...      None             no
7  the name of the country where each customer re...      None             no

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
wholesale_customers = fetch_ucirepo(id=292) 
  
# data (as pandas dataframes) 
X_wholesale_customers = wholesale_customers.data.features 
y_wholesale_customers = wholesale_customers.data.targets 
  
# metadata 
print(wholesale_customers.metadata) 
  
# variable information 
print(wholesale_customers.variables)

{'uci_id': 292, 'name': 'Wholesale customers', 'repository_url': 'https://archive.ics.uci.edu/dataset/292/wholesale+customers', 'data_url': 'https://archive.ics.uci.edu/static/public/292/data.csv', 'abstract': 'The data set refers to clients of a wholesale distributor. It includes the annual spending in monetary units (m.u.) on diverse product categories', 'area': 'Business', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 440, 'num_features': 7, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['Region'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2013, 'last_updated': 'Mon Feb 05 2024', 'dataset_doi': '10.24432/C5030X', 'creators': ['Margarida Cardoso'], 'intro_paper': None, 'additional_info': {'summary': None, 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '1)\tFRESH: annual spending (m.u.) on fresh products (Continuous);\r\n2)\tMILK: annual spending (m.u.) on milk products (Continuous);\r\n3)\tGROCERY: annual spending (m.u.)on grocery products (Continuous);\r\n4)\tFROZEN: annual spending (m.u.)on frozen products (Continuous)\r\n5)\tDETERGENTS_PAPER: annual spending (m.u.) on detergents and paper products (Continuous) \r\n6)\tDELICATESSEN: annual spending (m.u.)on and delicatessen products (Continuous); \r\n7)\tCHANNEL: customersâ€™ Channel - Horeca (Hotel/Restaurant/CafÃ©) or Retail channel (Nominal)\r\n8)\tREGION: customersâ€™ Region â€“ Lisnon, Oporto or Other (Nominal)\r\nDescriptive Statistics:\r\n\r\n\t(Minimum, Maximum, Mean, Std. Deviation)\r\nFRESH (\t3, 112151, 12000.30, 12647.329)\r\nMILK\t(55, 73498, 5796.27, 7380.377)\r\nGROCERY\t(3, 92780, 7951.28, 9503.163)\r\nFROZEN\t(25, 60869, 3071.93, 4854.673)\r\nDETERGENTS_PAPER (3, 40827, 2881.49, 4767.854)\r\nDELICATESSEN (3, 47943, 1524.87, 2820.106)\r\n\r\nREGION\tFrequency\r\nLisbon\t77\r\nOporto\t47\r\nOther Region\t316\r\nTotal\t440\r\n\r\nCHANNEL\tFrequency\r\nHoreca\t298\r\nRetail\t142\r\nTotal\t440\r\n', 'citation': None}}
               name     role         type demographic description units  \
0           Channel  Feature  Categorical        None        None  None
1            Region   Target  Categorical        None        None  None
2             Fresh  Feature      Integer        None        None  None
3              Milk  Feature      Integer        None        None  None
4           Grocery  Feature      Integer        None        None  None
5            Frozen  Feature      Integer        None        None  None
6  Detergents_Paper  Feature      Integer        None        None  None
7        Delicassen  Feature      Integer        None        None  None

  missing_values
0             no
1             no
2             no
3             no
4             no
5             no
6             no
7             no

In [6]:
import pandas as pd

xlsx_online_retail = pd.read_excel('data/Online Retail.xlsx')
df_wholesale_customers = pd.read_csv('data/Wholesale customers data.csv')

In [ ]:
xlsx_online_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [18]:
df_wholesale_customers.head()

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [19]:
X = df_wholesale_customers.drop('Region', axis=1)
y = df_wholesale_customers['Region']